//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodS2Calories.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodS2Calories.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FOOD.
        /// </summary>
        public static string addfood {
            get {
                return ResourceManager.GetString("addfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW FOOD.
        /// </summary>
        public static string addnewfood {
            get {
                return ResourceManager.GetString("addnewfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Weight:.
        /// </summary>
        public static string addweight {
            get {
                return ResourceManager.GetString("addweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almonds.
        /// </summary>
        public static string almonds {
            get {
                return ResourceManager.GetString("almonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string apple {
            get {
                return ResourceManager.GetString("apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        public static string banana {
            get {
                return ResourceManager.GetString("banana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bread.
        /// </summary>
        public static string bread {
            get {
                return ResourceManager.GetString("bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter.
        /// </summary>
        public static string butter {
            get {
                return ResourceManager.GetString("butter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cake.
        /// </summary>
        public static string cake {
            get {
                return ResourceManager.GetString("cake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrot.
        /// </summary>
        public static string carrot {
            get {
                return ResourceManager.GetString("carrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereal.
        /// </summary>
        public static string cereal {
            get {
                return ResourceManager.GetString("cereal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheese.
        /// </summary>
        public static string cheese {
            get {
                return ResourceManager.GetString("cheese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        public static string chocolate {
            get {
                return ResourceManager.GetString("chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERT.
        /// </summary>
        public static string convert {
            get {
                return ResourceManager.GetString("convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cream.
        /// </summary>
        public static string cream {
            get {
                return ResourceManager.GetString("cream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT FOODS.
        /// </summary>
        public static string editfood {
            get {
                return ResourceManager.GetString("editfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg.
        /// </summary>
        public static string egg {
            get {
                return ResourceManager.GetString("egg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic.
        /// </summary>
        public static string garlic {
            get {
                return ResourceManager.GetString("garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glicids(per 100g):.
        /// </summary>
        public static string glicid {
            get {
                return ResourceManager.GetString("glicid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where you attempting some guinness world record?.
        /// </summary>
        public static string guiness {
            get {
                return ResourceManager.GetString("guiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettuce.
        /// </summary>
        public static string lettuce {
            get {
                return ResourceManager.GetString("lettuce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lipids(per 100g):.
        /// </summary>
        public static string lipid {
            get {
                return ResourceManager.GetString("lipid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango.
        /// </summary>
        public static string mango {
            get {
                return ResourceManager.GetString("mango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEAL CALCULATOR.
        /// </summary>
        public static string mealcalculator {
            get {
                return ResourceManager.GetString("mealcalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your meal.
        /// </summary>
        public static string mealinsert {
            get {
                return ResourceManager.GetString("mealinsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reset the food table to its original definitions..
        /// </summary>
        public static string mesage1 {
            get {
                return ResourceManager.GetString("mesage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string mesage2 {
            get {
                return ResourceManager.GetString("mesage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        public static string milk {
            get {
                return ResourceManager.GetString("milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushrooms.
        /// </summary>
        public static string mushrooms {
            get {
                return ResourceManager.GetString("mushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive oil.
        /// </summary>
        public static string oliveoil {
            get {
                return ResourceManager.GetString("oliveoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion.
        /// </summary>
        public static string onion {
            get {
                return ResourceManager.GetString("onion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasta.
        /// </summary>
        public static string pasta {
            get {
                return ResourceManager.GetString("pasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pea.
        /// </summary>
        public static string pea {
            get {
                return ResourceManager.GetString("pea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peach.
        /// </summary>
        public static string peach {
            get {
                return ResourceManager.GetString("peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pear.
        /// </summary>
        public static string pear {
            get {
                return ResourceManager.GetString("pear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza.
        /// </summary>
        public static string pizza {
            get {
                return ResourceManager.GetString("pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes.
        /// </summary>
        public static string potatoes {
            get {
                return ResourceManager.GetString("potatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proteins(per 100g):.
        /// </summary>
        public static string protein {
            get {
                return ResourceManager.GetString("protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red meat.
        /// </summary>
        public static string redmeat {
            get {
                return ResourceManager.GetString("redmeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET FOODS.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rice.
        /// </summary>
        public static string rice {
            get {
                return ResourceManager.GetString("rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings2 {
            get {
                return ResourceManager.GetString("settings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrimp.
        /// </summary>
        public static string shrimp {
            get {
                return ResourceManager.GetString("shrimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar.
        /// </summary>
        public static string sugar {
            get {
                return ResourceManager.GetString("sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomatoes.
        /// </summary>
        public static string tomatoes {
            get {
                return ResourceManager.GetString("tomatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS.
        /// </summary>
        public static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!!!.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White meat.
        /// </summary>
        public static string whitemeat {
            get {
                return ResourceManager.GetString("whitemeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yogurt.
        /// </summary>
        public static string yogurt {
            get {
                return ResourceManager.GetString("yogurt", resourceCulture);
            }
        }
    }
}
